### ISSUE TITLE
Getting TypeError: Cannot read property 'reduce' of undefined followed by 401 unauthorized

### ISSUE THREAD

**Issue by chandankhatri** [commercetools/commercetools-sunrise-data#120]
projectKey: sunrise-40
clientId: ex7c--------AOuet
clientSecret: CkNNfNojt-----------ZM0M
authUrl: https://auth.commercetools.co
apiUrl: https://api.commercetools.co
--------------------------------------------------------
TypeError: Cannot read property 'reduce' of undefined
    at run (/Users/admin/Documents/GitHub/commercetools-sunrise-data/dist/lib/shipping-method.js:62:55)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:21682) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reduce' of undefined
    at run (/Users/admin/Documents/GitHub/commercetools-sunrise-data/dist/lib/shipping-method.js:62:55)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:21682) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21682) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

---------
--------------------------------------------------------
projectKey: sunrise-40
clientId: ex--------9VAOuet
clientSecret: CkNNfNojt6s1------ZM0M
authUrl: https://auth.commercetools.co
apiUrl: https://api.commercetools.co
--------------------------------------------------------

> sunrise@1.0.0 import:categories /Users/admin/Documents/GitHub/commercetools-sunrise-data
> category-sync import -f data/categories.csv -p $npm_package_config_projectKey --clientId $npm_package_config_clientId  --clientSecret $npm_package_config_clientSecret

Process row: 2
{"name":"sphere-category-sync-1.1.2","hostname":"US-DA1LPMAC0137","pid":21714,"level":50,"data":{"body":{"statusCode":401,"message":"Please provide valid client credentials using HTTP Basic Authentication.","errors":[{"code":"invalid_client","message":"Please provide valid client credentials using HTTP Basic Authentication."}],"error":"invalid_client","error_description":"Please provide valid client credentials using HTTP Basic Authentication.","originalRequest":{"endpoint":"/categories?where=externalId%20in%20(%221%22)&sort=id%20asc","options":{"config":{"project_key":"sunrise-40"},"host":"api.sphere.io","protocol":"https","timeout":20000,"rejectUnauthorized":true,"headers":{"User-Agent":"sphere-node-sdk"},"uri":"https://api.sphere.io/sunrise-40","gzipEnable":true}}},"message":"Please provide valid client credentials using HTTP Basic Authentication.","name":"Unauthorized","stack":"Unauthorized: Please provide valid client credentials using HTTP Basic Authentication.","code":401,"statusCode":401},"project_key":"sunrise-40","msg":"undefined","time":"2019-03-12T11:17:23.743Z","v":0}

**Comment by plaskevich** [comment]
Fixed in #131
