### ISSUE TITLE
All category names should be of format 'Name'

### ISSUE THREAD

**Issue by peter-gerhard** [commercetools/commercetools-sunrise-data#13]
first letter upper case, rest lower

**Comment by schleichardt** [comment]
Why? With css you can uppercase the first letter.

**Comment by hajoeichler** [comment]
You want to use the name of the category also for the title of the page, which can't be adapted by CSS.

**Comment by hajoeichler** [comment]
@emmenko could you please once check the name.it column if ok.

**Comment by hajoeichler** [comment]
@lauraluiz and @peter-gerhard some english names are combined of several words.
Should it be 
- `Bucketbag & packbag` or `Bucketbag & Packbag`
- `Fall in love` or `Fall In Love`

Same question goes to italian version @emmenko

**Comment by emmenko** [comment]
Do you want me to translate it or what? I see some names are kept to english. Is that how it is suppose to be?

**Comment by lauraluiz** [comment]
Bucketbag & Packbag in English and German, but not in Italian.

**Comment by peter-gerhard** [comment]
Bucketbag & Packbag
Fall in Love

**Comment by sshibani** [comment]
#Fixed
