### ISSUE TITLE
Error importing product data

### ISSUE THREAD

**Issue by saudsley-boden** [commercetools/commercetools-sunrise-data#134]
During the process to import data (using npm run start), when importing product data, the following error is raised

=====================================================

authUrl: https://auth.sphere.io
apiUrl: https://api.sphere.io
--------------------------------------------------------
Loading has finished
Initializing resources
Error: only absolute urls are supported
    at C:\...\commercetools-sunrise-data\node_modules\sphere-node-product-csv-sync\node_modules\@commercetools\sdk-middleware-auth\dist\commercetools-sdk-middleware-auth.cjs.js:4862:10
    at new Promise (<anonymous>)
    at new Fetch (C:\...\commercetools-sunrise-data\node_modules\sphere-node-product-csv-sync\node_modules\@commercetools\sdk-middleware-auth\dist\commercetools-sdk-middleware-auth.cjs.js:4857:9)

==============================================

The previous steps importing customers & category data works correctly (and I can see the data in merchant center)

**Comment by pravin-logicap** [comment]
Getting same error, 
Am I missing something here?

**Comment by asmagin** [comment]
Was this fixed?

**Comment by asmagin** [comment]
For some reason in file `\node_modules\sphere-node-product-csv-sync\node_modules\@commercetools\sdk-middleware-auth\dist\commercetools-sdk-middleware-auth.cjs.js` URL coming with incorrect slashes, which causes issues in url parsers.

This hack fixed the issues for me.
``` js
# line:4753
function Request(input, init) {
	var url$$1, url_parsed;

	// normalize input
	if (!(input instanceof Request)) {
		url$$1 = input.replace('\\', '//');
		url_parsed = parse_url(url$$1);
		input = {};
	} else {
		url$$1 = input.url.replace('\\', '//');
		url_parsed = parse_url(url$$1);
	}
```

**Comment by pravin-logicap** [comment]
Yes, the Same hack worked for me also

**Comment by pemko123** [comment]
Is this maybe a Windows Problem? Slashes are different on windows than on linux/mac

**Comment by harm-meijer** [comment]
Removing the sphere dependencies has solved this problem. New release works on Windows as well.
