### ISSUE TITLE
"npm run import:inventory" gives "Unhandled rejection Unauthorized: Please provide valid client credentials using HTTP Basic Authentication"

### ISSUE THREAD

**Issue by mlevin2** [commercetools/commercetools-sunrise-data#147]
I'm having some problems with the optional inventory import.

The `npm run start` import works fine, but the `npm run import:inventory` script gives me several lines of this error:

```
Unhandled rejection Unauthorized: Please provide valid client credentials using HTTP Basic Authentication.
```

**Comment by SvetlanaKovaleva** [comment]
It works for me.

"import:inventory": "cross-env-shell \"node_modules/.bin/stock-import import --file data/inventory.csv --projectKey $npm_package_config_projectKey --clientId $npm_package_config_clientId --clientSecret $npm_package_config_clientSecret --sphereHost \"$npm_package_config_apiUrl\" --sphereAuthHost \"$npm_package_config_authUrl\"\"",

**Comment by harm-meijer** [comment]
The new release will get this information from the `.env` file.
