### ISSUE TITLE
Importing products fails when prices use country *and* customer group

### ISSUE THREAD

**Issue by m0wlheld** [commercetools/commercetools-sunrise-data#157]
Tried to change some prices in [products.csv](./data/products.csv) and encountered an error:

When using a price with country code **and** customer group, the currency string (e.g. DE-EUR) is used without interpretation, causing the value to be rejected by API

These examples do work:
* EUR 599
* EUR 499 b2c
* DE-EUR 599

This example does not work:
* DE-EUR 599 b2c

Reason is, that in file [products.js](./lib/products.js), line [136](https://github.com/commercetools/commercetools-sunrise-data/blob/25bcad165bd3283115d9b0b26404322a90fc4082/lib/products.js#L136) the currency value is returned immediately, as soon as a customer group is defined. The actual converting of currencies like "DE-EUR" (line [152](https://github.com/commercetools/commercetools-sunrise-data/blob/25bcad165bd3283115d9b0b26404322a90fc4082/lib/products.js#L152)) is skipped.

**Comment by harm-meijer** [comment]
@m0wlheld I think [this](https://github.com/commercetools/commercetools-sunrise-data/pull/158) fixes the bug.
