### ISSUE TITLE
Error on importing data

### ISSUE THREAD

**Issue by nitinsingh5678** [commercetools/commercetools-sunrise-data#167]
>npm run start

> sunrise@1.0.0 start ..\commercetools-sunrise-data-master
> npm run build && node dist/lib/data.js --start
> sunrise@1.0.0 build ..\commercetools-sunrise-data-master
> rimraf dist/ && babel ./lib/*.js --out-dir dist/lib/ --ignore ./node_modules,./.babelrc,./package.json,./npm-debug.log --copy-files

Successfully compiled 20 files with Babel.
  --------------------------------------------------------
projectKey: ****
clientId: ****
clientSecret: ****
authUrl: https://auth.us-**
apiUrl: https://api.us-**
--------------------------------------------------------
--Deleting all project data--
Deleting products
Failed to delete products, see import-error.log for more details
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sunrise@1.0.0 start: `npm run build && node dist/lib/data.js --start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sunrise@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     _logs\2020-07-01T13_25_34_677Z-debug.log

I have master branch, if I see the import-error log file I found below error:
"stack": "TypeError: fetcher(...).then(...).finally is not a function\n    at executeFetch

**Comment by harm-meijer** [comment]
> Failed to delete products, see import-error.log for more details

Is there a file called import-error.log

**Comment by harm-meijer** [comment]
Did you try removing node_modules and installing dependencies again with `npm insall`?

**Comment by nitinsingh5678** [comment]
Thanks for the suggestion, after upgrading with latest node version it worked properly. It will be much helpful if required minimum node version is mentioned in document.
