### ISSUE TITLE
Add variant key to products.csv so data can be used to test import-api 

### ISSUE THREAD

**Issue by briantomkins** [commercetools/commercetools-sunrise-data#191]
Add variant key to products so data can be used to test import-api 

- repeat sku as key

**Comment by harm-meijer** [comment]
@briantomkins Would you like an extra column in [products.csv](https://github.com/commercetools/commercetools-sunrise-data/blob/master/data/products.csv) that has (sku)-(variant index) so you can use it as key of the [product variant draft](https://docs.commercetools.com/api/projects/products#productvariantdraft)?

**Comment by briantomkins** [comment]
Hi @harm-meijer yes repeating the sku and variantKey would be acceptable to the customer. Thanks
