### ISSUE TITLE
Provide an option to import smaller data that fit the trial project restrictions

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-data#43]
Our Trial mode projects are limited (e.g. 5k products), which is why this importer fails hard. 

It would be good to have an option to import only a subset that fits trial projects.

**Comment by schleichardt** [comment]
That is already possible, how do did you try it, so that it does not work for you?

see https://github.com/commercetools/commercetools-sunrise-data/tree/master/importApp job `productsCreateJob`. 

The importable Sunrise product data does exceed 3000 products.

**Comment by nkuehn** [comment]
I actually did not try myself - I got the feedback from Training participants and partner employees. 

Could it be that it duplicates the products if you import them again?  Maybe they accidentally ran it  twice.

**Comment by schleichardt** [comment]
Yes, that definitively could cause errors.

**Comment by nkuehn** [comment]
So we do not set a SKU?  That's checked for uniqueness platform-side and should not allow duplicate products or variants. 

We'll just have to try out in the End.

**Comment by sshibani** [comment]
Resolved, by using standard product sync library
