### ISSUE TITLE
Add order data to Sunrise 

### ISSUE THREAD

**Issue by Oehmi** [commercetools/commercetools-sunrise-data#76]
**Current situation**
In order to  test the product recommendations feature on Sunrise Staging, we first have to enhance the **order data** in Sunrise, as the current orders are not sufficient. 
There is a new CSV with test order data, but we were not able to convert the CSV into a proper JSON file due to the complexity of the order object, and we cannot import the CSV otherwise. 

**Desired solution**
Therefore, we would like to implement the new order data directly into Sunrise. The file consists only a bare minimum of required fields for an order, such as 
customer email (instead of customer id), SKU, price, quantity, line item name

The currently existing order can be removed from Sunrise. 

Please ask Steffi for the CSV

**Comment by acbeni** [comment]
@Oehmi The upload has been done to sunrise demo, the deployment of the batch application will be done later.

**Comment by sshibani** [comment]
done
