### ISSUE TITLE
Add import of cart discount and discount codes

### ISSUE THREAD

**Issue by katmatt** [commercetools/commercetools-sunrise-data#88]
Since impex doesn't support cart discounts yet, it would be nice if we could add a json import for it to our import app. Discount codes are supported by impex, but I haven't tried how difficult it is to connect the discount code with the cart discounts. But of course it would be nice if we could impex instead of writing our own discount code import.

**Comment by lauraluiz** [comment]
We can also consider just documenting the discounts that we want by default in the documentation, together with the other Admin Center configurations. And then analize which long-term solution will be better according to IMPEX's roadmap.

**Comment by lauraluiz** [comment]
(Ah, unless it's too much information 😉 )

**Comment by sshibani** [comment]
Closed. Moved into specific issues for specific discount type
