### ISSUE TITLE
separate basic inventory and channel-specific inventory CSV

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-data#89]
Most demo setups don't need the per-channel data fully exploded but the CSV with the inventory is one big block including inventories for all channels.  

Downsides:
 * if you run the inventory generation job after having done the basic steps it fails and it's unclear why (the available jobs should not collide)
 * the standard inventory generation runs very long and creates masses of data which is not necessary in most

short form:  the previous "importApp" setup was more realistic - default documentation does not generate prices and inventories per channel, but you can do it.

**Comment by lauraluiz** [comment]
Duplicated #82

**Comment by lauraluiz** [comment]
@sshibani this is solved in the java app, I guess we can close it?
